[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/icons"
  to = "/.netlify/functions/icons"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200